### PR TITLE
Respect user predefined fzf layout config

### PR DESCRIPTION
**Pull request by PlankCipher**
This is how my fzf window (triggered with :Files) usually looks like:
good

But after installing `dashboard-nvim`, if I trigger fzf through it, for example by pressing enter on `Find file` or `Recently opened files` at the dashboard screen, `dashboard-nvim` overrides my fzf appearance and layout related config to make it look like this:
bad

I found that very inconvenient. So, I removed these lines from `autoload/dashboard/fzf.vim` to preserve my fzf layout config. I tested this fix out, and it didn't break anything AFAIK.

PS: I think I noticed it checks if `g:dashboard_fzf_window` equals `1` before overriding my config. So, I tried setting it to `0`, but this didn't fix it.

### CODE REVIEW

**Comment by glepnir** [comment]
you can disable dashboard fzf window `let g:dashboard_fzf_window = 0`

**Comment by PlankCipher** [comment]
> you can disable dashboard fzf window `let g:dashboard_fzf_window = 0`

Already tried, didn't work.

**Comment by glepnir** [comment]
hmm my plan that rewrite dashboard by using lua. so this will be change when i rewrite.

**Comment by PlankCipher** [comment]
Great idea. However, consider merging this pull request or fix the bug in any other way for now.

**Comment by glepnir** [comment]
Your pr is destructive, it deletes all fzfwindow code. I am not sure if others are satisfied with the current fzf window. My suggestion you can rewrite the code of fzf window to use your window code

**Comment by PlankCipher** [comment]
I think this is better.

**Pull request merged**
