### PR TITLE
break change new version 0.2.3

### PR DESCRIPTION
**Pull request by glepnir**
refactor all dashboard

## zero memory usage 
  now dashboard does not store the all user configs in memory like header etc these string will take some memory. now it will be clean after you open a file.  you can still use dashboard command to open a new one , then 
dashboard will read the config from cache.

## Blazing fast
  async based on luv file system .

### CODE REVIEW

**Comment by glepnir** [comment]
image

**Comment by glepnir** [comment]
the modern theme is async based on luv file system.

image

**Comment by glepnir** [comment]
all refactor done .

**Comment by glepnir** [comment]
image

**Comment by Raagh** [comment]
as seen in the doom picture, dashboard show the same key on item 1 and 2 of the table. also key is mandatory so if you want to use your keymaps and just use dashboard as a display, you cant'

**Comment by Raagh** [comment]
> @Raagh Same issue for me, also I don't really get why icons were removed from Doom theme... it would also be good to constrain cursor movement to center lines and be able to use `<CR>` to select the item, or hide cursor entirely.

I had the icons as part of my text so I didn't noticed that. Yes, I don't like that the cursor is useless now, it would nice to move around the options with the keys as before.

**Comment by rebelot** [comment]
What was nice about explicit icons was that one could configure icon highlight, desc highlight and key highlight separately. ;)

**Comment by glepnir** [comment]
it just an example picture .. I don't notice that the key is duplicate .will udpate new one .

> configure icon highlight, desc highlight and key highlight separately

easy support but it will config a little long.  if user think it does not matter.

**Comment by rebelot** [comment]
> it just an example picture .. I don't notice that the key is duplicate .will udpate new one .
> 
> > configure icon highlight, desc highlight and key highlight separately
> 
> easy support but it will config a little long. if user think it does not matter.

Many users that posted their config in the appropriate issue had defined their own colors for icons, also in the wiki. I think it'd be nice to restore that behaviour, maybe the fields can be optional.

**Comment by glepnir** [comment]
now add it support if not config these highlight group it will use builtin like string number title
```lua
local db = require('dashboard')
db.setup({
  theme = 'doom',
  config = {
    center = {
      {
        icon = ' ',
        icon_hl = 'Title',
        desc = 'Recently latest session',
        desc_hi = 'String',
        key = 's',
        key_hi = 'Number',
        action = 'SessionLoad'
      },
      {
        icon = ' ',
        icon_hl = 'Title',
        desc = 'Find File',
        desc_hi = 'String',
        key = 'b',
        key_hi = 'Number',
        action = 'SessionLoad'
      },
      {
        icon = ' ',
        icon_hl = 'Title',
        desc = 'Find Dotfiles',
        desc_hi = 'String',
        key = 'f',
        key_hi = 'Number',
        action = 'SessionLoad'
      },
    }

  }
})

```

**Comment by glepnir** [comment]
about cursor. currently you don't need move cursor just press the key . i think it fast and useful than press j or k to move and press enter.

**Comment by Raagh** [comment]
> 

I was refering that the picture show my issue. The first kjey is indeed duplicate no matter what I put as key

imagen

**Comment by glepnir** [comment]
hmm how do you config it ? now the key a buffer map in dashboard buffer not your keymap.  like `key = s` press s in dashboard it will run the action

**Comment by glepnir** [comment]
oh reproduced wait.

**Comment by glepnir** [comment]
fixed.

**Comment by Raagh** [comment]
> 

pressing the key is fine, but moving and pressing enter is not as easy when the cursor moves over the entire screen. It would be easier to do that if it would move over the elements as it use to did

**Comment by glepnir** [comment]
supported. the cursor work likes before.

**Comment by glepnir** [comment]
I most like hyper 🍶

**Comment by Raagh** [comment]
> 

Thanks for the quick fixes, I can now move through the elements just fine but how do you select them? Enter seems to just jump to the next line, not trigger the element action

**Comment by rebelot** [comment]
```lua
    {
        desc = 'TEST1',
        icon = '  ',
        icon_hi = "Keyword",
        desc_hi = "DashboardCenter",
        key = 't1'
    },
    {
        desc = 'TEST2',
        icon = '  ',
        icon_hi = "Comment",
        key = 't2',
    },
    {
        desc = 'TEST3',
        icon = '  ',
        key = 't3',
    }

```

Screenshot 2023-01-25 at 12 47 31

* off-by-one error in `icon_hi`, `desc_hi` and `key`
* default highlight for `desc` in Doom is NOT `DashboardCenter` anymore, and must be set explicitly.
* `icon` does not work if it is a simple ascii character (e.g. `icon = "A"`, does not render the icon as separate from text)
* `*_hi` should be `*_hl`


I would suggest not to use `String` `Title` etc, directly,  but do something like
```
hi default link DashBoardIcon Keyword
hi default link DashBoardDesc Identifier
hi default link DashBoardKey Special
etc ...
```
so that colorscheme maintainers can override them...

**Comment by glepnir** [comment]
> > 
> 
> Thanks for the quick fixes, I can now move through the elements just fine but how do you select them? Enter seems to just jump to the next line, not trigger the element action

fix cr map i use hyper mostly

**Comment by glepnir** [comment]
> icon does not work if it is a simple ascii character (e.g. icon = "A", does not render the icon as separate from text)

yep currently use regex `%w` to find the first character. i assume people use the icon or emoji . ignored the ascii text.

**Comment by glepnir** [comment]
fixed and added those highlight groups

**Comment by rebelot** [comment]
> > icon does not work if it is a simple ascii character (e.g. icon = "A", does not render the icon as separate from text)
> 
> yep currently use regex `%w` to find the first character. i assume people use the icon or emoji . ignored the ascii text.

assuming that each line is : `entering_offset .. icon .. desc .. key`
```
icon_start = centering_offset
icon_end = icon_start + vim.fn.strdisplaywidth(icon)
desc_start = icon_end
desc_end = ....
```
and just add highlights using extmarks

**Comment by glepnir** [comment]
hmm i had fixed it i think it not works for you ?

**Comment by rebelot** [comment]
> hmm i had fixed it i think it not works for you ?

It works, assuming icon is exactly one ascii character. You did not set default values of  the new highlight groups

**Comment by glepnir** [comment]
> assuming icon is exactly one ascii character

nope AA BB also work. yep I don't set color for default highlight groups . colorscheme or user config it :)

**Comment by glepnir** [comment]
there can be find last space by using `(%s+)`  then last space col + api.nvim_strwidth(icon) .  currently way also works fine. so if get a bug then changed that way ...

**Comment by rebelot** [comment]
> > assuming icon is exactly one ascii character
> 
> nope AA BB also work. yep I don't set color for default highlight groups . colorscheme or user config it :)

"A  B" does not. Not a problem tho, just found an edge case by accident :)

Thanks for the good work glepnir!!!

**Comment by glepnir** [comment]
hmm the latest ?  it works fine 

image

**Comment by rebelot** [comment]
Works fine with latest :)

**Comment by LeonHeidelbach** [comment]
@glepnir Why did you completely remove the session functionality from Dashboard? This removes almost the entire usefulness of this plugin for me...

**Comment by glepnir** [comment]
because as a start screen plugin speed is first . load some session code will take some startup time.  and the session.in dashboard before is.simply. there has some session plugins. if you like before session you can find them and copy to your config.

**Comment by LeonHeidelbach** [comment]
@glepnir The speed differential between loading a couple hundred lines of code more into the memory is absolutely negligible, especially since the code does not even do anything without a manual trigger. You can even run benchmarks to confirm this. 

However, what is really bad is to simply remove an entire branch of features from a plugin that many people use exactly for the previously proposed feature set. Of course I could simply copy the code to my own config and implement everything myself but that's not the point here. Crippling your plugin just like that with a single breaking change for a speed improvement that yields at best a couple of micro or even pico seconds is most definitely not the way to go and in my opinion a poor choice to go forward with Dashboard, which up until now has been my favorite Splash Screen plugin. I hope you reconsider...

**Comment by rebelot** [comment]
> @glepnir The speed differential between loading a couple hundred lines of code more into the memory is absolutely negligible, especially since the code does not even do anything without a manual trigger. You can even run benchmarks to confirm this.
> 
> However, what is really bad is to simply remove an entire branch of features from a plugin that many people use exactly for the previously proposed feature set. Of course I could simply copy the code to my own config and implement everything myself but that's not the point here. Crippling your plugin just like that with a single breaking change for a speed improvement that yields at best a couple of micro seconds or even just a few pico seconds is most definitely not the way to go and in my opinion a poor choice to go forward with Dashboard, which up until now has been my favorite Splash Screen plugin. I hope you reconsider...

In total honesty, I prefer tools that do one thing and do it well. Dashboard implementation of sessions was really too simplistic. There are many plugins out there for thorough session/project management that do simple to complex stuff and you don't have any duplicate functionality for the sake of clean-ness.

**Comment by LeonHeidelbach** [comment]
> > @glepnir The speed differential between loading a couple hundred lines of code more into the memory is absolutely negligible, especially since the code does not even do anything without a manual trigger. You can even run benchmarks to confirm this.
> > However, what is really bad is to simply remove an entire branch of features from a plugin that many people use exactly for the previously proposed feature set. Of course I could simply copy the code to my own config and implement everything myself but that's not the point here. Crippling your plugin just like that with a single breaking change for a speed improvement that yields at best a couple of micro seconds or even just a few pico seconds is most definitely not the way to go and in my opinion a poor choice to go forward with Dashboard, which up until now has been my favorite Splash Screen plugin. I hope you reconsider...
> 
> In total honesty, I prefer tools that do one thing and do it well. Dashboard implementation of sessions was really too simplistic. There are many plugins out there for thorough session/project management that do simple to complex stuff and you don't have any duplicate functionality for the sake of clean-ness.

I do agree with you on that but the thing is that I don't need a fancy session management solution or another plugin that potentially has many features, that I don't need or use. The nice thing here was that the session feature had exactly the amount of functionality that is necessary. If Dashboard never had a builtin session feature I would be completely on your side but in my opinion removing so much of an established set of features just like that is never a good choice, even for simplicity's sake.

**Comment by glepnir** [comment]
First of all, thank you for your liking. Secondly, I understand what you said and how you feel. This is a persistent problem. As a startup screen plug-in, there should be no session function. But at that time, vim only had the startify, which provided the session function. There were also some session codes in my own configuration at that time, so I put them into the dashboard, which is actually wrong, It doesn't just load a file with hundreds of lines. It needs to call nvim_ create_ user_ The command function registers commands, which will take some time. A session plug-in should use command for lazy load calls instead of registering at vim startup. I will implement an asynchronous session plug-in about session, which will be faster than the previous one. If you need it

**Comment by LeonHeidelbach** [comment]
At the end of the day it's your choice. If you really want to remove the entire session feature I will have to look elsewhere. I don't really see the concept of a dashboard plugin clashing too much with a function that enables you to restore a session right from the splash screen. I think I will most likely just pin the last working commit before the breaking change for now. Modern computers are really fast (I would also consider a 10 year old laptop modern enough), and even registering multiple user commands will not have a noticable impact on the startup time. I have just released my first standalone neovim plugin a couple of days ago, and also did some benchmarks to measure any performance impact. I also register quite a few user commands and it is not noticable in the benchmarks. If you are interested in developing a new super simple session manager plugin I will definitely check it out :+1:.

**Comment by glepnir** [comment]
https://github.com/glepnir/dbsession.nvim

**Pull request merged**
