### PR TITLE
Fix: fix the bug when cache file is empty or not exist

### PR DESCRIPTION
**Pull request by YangEfei**
If this conditional judgment is placed in the original position, it will stop at `if #plist > 15 then`. So I removed it to later, and the logic of judgment here seems more in line with the original needs.

### CODE REVIEW

**Comment by glepnir** [comment]
this is not correct

**Comment by YangEfei** [comment]
This problem does exist.
However, when I tried to change it to
```lua
plist = vim.list_slice(plist, #plist - 14, #plist)
```
I met the same error about malformed bytecode which I mentioned yesterday: https://github.com/glepnir/dashboard-nvim/issues/284
If the size of `plist` reach the limit, it maybe cause it.

I found that there're some disorderly code in the cache file.
image

And the plist will be double. One in list, and other out of list.
I have tried to remove the other text int the cache file, only leave `return { ... }` in it. It works correctly.
So I think there're some errors about encoding of writing files.

**Comment by YangEfei** [comment]
I set the slice size to 2 now.
And I found a way to reproduce this malformed bytecode error stably.
If I open a project which may have 2 lsp_root_directory (as `~/.config/nvim` and `~/.config` in below screenshot), and the size of cache is over limit, it will crash.
image
You can find that the size of list in `return {...}` is 2, but out of it, there're 4.
The part which out of `return {...}` seems not correct due to it lose some characters.

image
And then I modify this cache manually like above, there will be no errors.

**Comment by glepnir** [comment]
hmm it's dump bytecode not `malformed bytecode` i think..

**Comment by YangEfei** [comment]
I modified the commit.

And I tried a small demo to verify the usage of `loadstring(string)` and `string.dump(function)`.
I think these functions are symmetric logic. We don't need to create a function which wrap the string and dump the string from the function again. And it will lead to the disorderly code which I mentioned above.
So I remove it, just concat the string together and dump into cache file.
I have verified it, and works correctly.

**Comment by glepnir** [comment]
interesting test. so that's mean just write the return string into cache then read it and passed to `loadstring` it can still work right?

**Comment by YangEfei** [comment]
yup. as a matter of fact, we even needn't to use `loadstring` to read the cache file, because it just execute the string which wrap in `loadstring`. So if we set `return { "a"} ` in the cache file, when we run `loadstring(data)` we will get { "a" } as below.
image
But I think `loadstring` can construct the table, so I don't remove it when reading file, just remove it from the dump logic.

**Comment by glepnir** [comment]
okay then can keep the remove code in top ? remove in latest not correct. because the show index in start  from tail

**Comment by YangEfei** [comment]
I have changed the slice logic in the latest commit to obtain the latest 15 projects. https://github.com/glepnir/dashboard-nvim/commit/e0d96b0cdb70547366c88c29645fa166fa7ed0ad
Revert this modification is ok, but we need to add a defensive check before use `#plist`
```lua
if plist ~= nil and #plist > 15 then
```
Because if the cache file is empty ,it will get error here.
This was my original reason for modifying this part of the code.

**Comment by glepnir** [comment]
if cache is empty before will be nil i guess.

**Comment by YangEfei** [comment]
And I found the reason why it cause malformed bytecode.
It not due to `string.dump`. Just because it not clear the file after slice, and just overwrite the length of new plist.
See the screenshot below:
image
The directory out of `{}` which I marked is the previous plist, and it still here even though the plist has been sliced.

**Comment by glepnir** [comment]
likt this.  list_slice still in head. not after list_extend
```lua
            local plist = before()
            if plist and #plist > 15 then
              plist = vim.list_slice(plist, 15)
            end
            plist = vim.tbl_filter(function(k)
```

**Comment by YangEfei** [comment]
image
Yup. But the empty cache file will get `nil` by fs_read. I have tested too

**Comment by glepnir** [comment]
if plist  same as `if plist ~= nil`

**Comment by YangEfei** [comment]
```lua
local uv = vim.loop
local fd = uv.fs_open("/home/yangyifei.yyf/.cache/nvim/dashboard/cache", "rs+", 438)
uv.fs_write(fd, 'test', 0)
uv.fs_close(fd)
```
I have tested `fs_write` by a simple test, and the result is below:
image

You can see that only first 4 chars are instead by 'test'.

**Comment by YangEfei** [comment]
I have fixed this error by `fs_ftruncate`.
There're 2 ways to implementing read and overwrite the same file.
1. Open file with flag `r` to get the data, and close it. Open file again with flag `w` to write back. `w` will open and clear the file so it can overwrite the file.
2. Just open the file with flag `r`, and do a truncate after write data to file.

I choose the second method. And I have verified it by myself~ No more errors.

**Comment by glepnir** [comment]
LGTM thx

**Pull request merged**
