### PR TITLE
ADD exit_key, FIX: README.md typo

### PR DESCRIPTION
**Pull request by NEX-S**
NOW WE CAN DEFINE `exit_key` IN SETUP FUNCTION.
ADD: `exit_key` TO EXIT THE DASHBOARD
ADD: `exit_key` DESCRIBE IN `README.md`
FIX: `README.md` typo

### CODE REVIEW

**Comment by NEX-S** [comment]
第一次提交，不太懂规矩，大佬见谅。
我在想有没有什么办法可以让自定义的快捷键如 `SPC X` 可以在 dashboard 里面生效，我会尝试去做一做 :+1:

**Comment by NEX-S** [comment]
DONE.

**Comment by spelb** [comment]
You don't really need for that option as you can add an option of Exit or Quit using neovim/vim build in :q command.
I used that the last option in my dashboard is Quit which the performs the action = ':q' and works very well

**Comment by NEX-S** [comment]
Plz take a look at my code. I have set a `custom_key` in order to use some keys only affect dashboard, this mean we can use keys like `a` `s` `d` `f` quick open some items we want.

**Comment by NEX-S** [comment]
In [29ce4d5](https://github.com/glepnir/dashboard-nvim/pull/178/commits/29ce4d5b3238672961caaff1f2fce2d389d79583)

**Pull request closed without merging**
