### PR TITLE
ADD `custom_key`

### PR DESCRIPTION
**Pull request by NEX-S**
Now we can use `custom_key` to set our own keymaps in dashboard.

### CODE REVIEW

**Comment by NEX-S** [comment]
I have set a custom_key in order to use some keys only affect dashboard, this mean we can use keys like a s d f quick open some items we want.

**Comment by spelb** [comment]
@NEX-S custom_keys just for dashboard will be great as there is the shortcut option in dashboard which will be used to display the key for specified option. It's a great idea.

**Comment by glepnir** [comment]
Like i said. why we need custom key. what is dashboard. show the shortcuts with some actions. if you had config the shorcut.just use shortcut. why do custom key?

**Comment by NEX-S** [comment]
What I think is in dashboard there is a tons of key that have been waste such as `a` `s` `d` `f`, so why not using these key to make our experience better?

**Comment by NEX-S** [comment]
> @NEX-S custom_keys just for dashboard will be great as there is the shortcut option in dashboard which will be used to display the key for specified option. It's a great idea. But I wonder that if it will affect the others key. like I have an option of Update Plugins in my dashboard and q is used to quit packers window. so If I run add key for q = quit for dashboard. Then will it affect the q for packers in dashboard option ?

as i test, q acts normal in packersync

**Pull request closed without merging**
